appwebmusic/urls.py
from django.contrib import admin
from django.urls import path
from MusicDLC.views import HomePageView, AddProductsView, LogUsersView, LogoutView, AddMarcaView, AddCategoriaView, GuitarsView, BassView, DrumsView, PianosView, ViolinesView, ConfirmPurchaseView, OrchestraView, SearchProductsView, ContactView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name="home"),
    path('agregar_productos/', AddProductsView.as_view(), name="agregar_productos"),
    path('agregar_marcas/', AddMarcaView.as_view(), name="agregar_marcas"),
    path('agregar_categorias/', AddCategoriaView.as_view(), name="agregar_categorias"),
    path('iniciar_sesion/', LogUsersView.as_view(), name="iniciar_sesion"),
    path('cerrar_sesion/', LogoutView.as_view(), name="cerrar_sesion"),
    path('guitarras/', GuitarsView.as_view(), name="guitarras"),
    path('bajos/', BassView.as_view(), name="bajos"),
    path('baterias/', DrumsView.as_view(), name="baterias"),
    path('teclados/', PianosView.as_view(), name="teclados"),
    path('violines/', ViolinesView.as_view(), name="violines"),
    path('orquesta/', OrchestraView.as_view(), name="orquesta"),
    path('buscar_productos/', SearchProductsView.as_view(), name='buscar_productos'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('confirmar_compra/', ConfirmPurchaseView.as_view(), name="confirmar_compra")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MusicDLC/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Marca(models.Model):
    nombre = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    
    def __str__(self):
        return self.nombre

class Instrumento(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad = models.IntegerField()
    disponibilidad = models.BooleanField(default=True)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="productos", null=True)
    
    def __str__(self):
        return f'Instrumento: {self.nombre}, Cantidad Disponibles: {self.cantidad}'
    
class Compra(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, default='')
    nombreCompleto = models.CharField(max_length=100)
    email = models.EmailField()
    telefono = models.CharField(max_length=20)
    productos = models.ManyToManyField(Instrumento, through='CompraProducto')
    precioFinal = models.DecimalField(max_digits=10, decimal_places=2)
    fechaCompra = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Compra realizada por: {self.usuario.username} el día {self.fechaCompra.date()}"

class CompraProducto(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    producto = models.ForeignKey(Instrumento, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    
    def __str__(self):
        return f"Cliente: {self.compra.nombreCompleto} - Producto: {self.producto.nombre} - {self.cantidad} unidades"

MusicDLC/forms.py
from django import forms
from .models import Categoria, Instrumento, Marca

class InstrumentosForm(forms.ModelForm):
    class Meta:
        model = Instrumento
        fields = ['nombre', 'descripcion', 'precio', 'cantidad', 'disponibilidad', 'marca', 'categoria', 'imagen']
        widgets = {
            'nombre': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese el Nombre del producto'
            }),
            'descripcion': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese una breve descripción'
            }),
            'precio': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese el Precio del producto'
            }),
            'cantidad': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese la Cantidad del producto'
            }),
            'disponibilidad': forms.CheckboxInput(attrs={
                'class': 'form-control',
            }),
            'marca': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese la Marca del producto'
            }),
            'categoria': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Seleccione la Categoria del producto'
            }),
            'imagen': forms.FileInput(attrs={
                'class': 'form-control',
            }),
        }
        error_messages = {
            'imagen': {
                'required': 'Por favor, cargue una imagen para el producto.',
            },
        }

class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ['nombre']
        widgets = {
            'nombre': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese nombre de la Marca'
            }),
        }
                
class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre', 'descripcion']
        widgets = {
            'nombre': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese la nueva Categoria'
            }),
            'descripcion': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese una breve descripción'
            }), 
        }

MusicDLC/views.py
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.views import View
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib import messages
from django.conf import settings
from django.db import IntegrityError
from django.db.models import Q
from django.core.mail import EmailMessage
from .forms import InstrumentosForm, CategoriaForm, MarcaForm
from .models import Categoria, Instrumento, Marca, Compra, CompraProducto
from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import AdminRequiredMixin

# Create your views here.
class HomePageView(View):
    def get(self, request):
        productos = Instrumento.objects.all()[:8]
        return render(request, 'index.html', {
            'productos' : productos
        })

class AddProductsView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request):
        form = InstrumentosForm()
        return render(request, 'agregar_productos.html', {
            'form' : form
        })
        
    def post(self, request):
        try:
            form = InstrumentosForm(request.POST, request.FILES)
            if form.is_valid():
                instrumento = form.save()
                instrumento.save()
                messages.success(request, f'El producto {instrumento.nombre} se agrego correctamente.')
                return redirect('agregar_productos')
            else:
                print(form.errors)
                return render(request, 'agregar_productos.html', {
                    'form' : form,
                    'error' : "Por favor, llene correctamente el formulario"
                })
        except ValueError:
            return render(request, 'agregar_productos.html', {
                'form' : InstrumentosForm(),
                'error' : "Porfavor agregue datos válidos."
            })
            
class ContactView(View):
    def post(self, request):
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        
        template = render_to_string('email_template.html', {
            'name' : name,
            'email' : email,
            'subject' : subject,
            'message' : message
        })
        
        email = EmailMessage(subject, template, settings.EMAIL_HOST_USER, ['soyjahirjesua04@gmail.com'])
        
        email.fail_silently = False
        email.send()
        
        messages.success(request, 'Se ha enviado el correo exitosamente!')
        return redirect('home')
            
class AddMarcaView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request):
        form = MarcaForm()
        return render(request, 'agregar_marcas.html', {
            'form' : form
        })
        
    def post(self, request):
        form = MarcaForm(request.POST)
        if form.is_valid():
            form = Marca.objects.create(nombre=request.POST['nombre'])
            form.save()
            if request.user.is_superuser and request.user.is_staff:
                messages.success(request, f'La marca {form.nombre} se agrego correctamente.')
                return redirect('agregar_marcas')
            else:
                return render(request, 'agregar_marcas.html', {
                    'MarcaForm': MarcaForm(),
                    'mensaje' : f'La marca {form.nombre} se agrego correctamente.'
                })
        else:
            return render(request, 'agregar_marcas.html', {
                'form': MarcaForm(),
                'error': 'Por favor, complete correctamente el formulario.'
            })
   
class AddCategoriaView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request):
        form = CategoriaForm()
        return render(request, 'agregar_categorias.html', {
            'form' : form
        }) 
    def post(self, request):
        form = CategoriaForm(request.POST)
        if form.is_valid():
            form = Categoria.objects.create(nombre=request.POST['nombre'], descripcion=request.POST['descripcion'])
            form.save()
            if request.user.is_superuser and request.user.is_staff:
                messages.success(request, f'La categoria {form.nombre} se agrego correctamente.')
                return redirect('agregar_categorias')
            else:
                return render(request, 'agregar_proveedores.html', {
                    'CategoriaForm' : CategoriaForm(),
                    'mensaje' : f'La categoria {form.nombre} se agrego correctamente.'
                }) 
        else:
            return render(request, 'agregar_proveedores.html', {
                'form': CategoriaForm(),
                'error': 'Por favor, complete correctamente el formulario de categoría.'
            })
   
class LogUsersView(View):
    def get(self, request):
        form_login = AuthenticationForm()
        form_register = UserCreationForm()
        error_message = request.GET.get('error')
        return render(request, 'iniciar_sesion.html', {
            'formLogin': form_login,
            'formRegister': form_register,
            'errorLogin': error_message
        })
        
    def post(self, request):
        form_login = AuthenticationForm()
        form_register = UserCreationForm()

        if 'login' in request.POST:
            form_login = AuthenticationForm(request, request.POST)
            if form_login.is_valid():
                username = form_login.cleaned_data['username']
                password = form_login.cleaned_data['password']
                Usuario = authenticate(request, username=username, password=password)
                if Usuario is not None:
                    login(request, Usuario)
                    return redirect('home')
                else:
                    return render(request, 'iniciar_sesion.html', {
                        'formLogin': form_login,
                        'formRegister': form_register,
                        'errorLogin': 'El Usuario ingresado no existe'
                    })
            else:
                return render(request, 'iniciar_sesion.html', {
                    'formLogin': form_login,
                    'formRegister': form_register,
                    'errorLogin': 'Usuario o contraseña incorrectos'
                })
                
        elif 'register' in request.POST:
            form_register = UserCreationForm(request.POST)
            if form_register.is_valid():
                usuario = form_register.save()
                login(request, usuario)
                return redirect('home')
            else:
                return render(request, 'iniciar_sesion.html', {
                    'formLogin': form_login,
                    'formRegister': form_register,
                    'errorRegister': 'Error en el formulario de registro',
                    'registerErrors': form_register.errors
                })

        return render(request, 'iniciar_sesion.html', {
            'formLogin': form_login,
            'formRegister': form_register
        })
        
class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('home')
    
class GuitarsView(View):
    def get(self, request):
        productos = Instrumento.objects.filter(categoria=1)
        return render(request, 'guitarras.html', {
            'productos' : productos
        })
        
class BassView(View):
    def get(self, request):
        productos = Instrumento.objects.filter(categoria=2)
        return render(request, 'bajos.html', {
            'productos' : productos
        })
        
class PianosView(View):
    def get(self, request):
        productos = Instrumento.objects.filter(categoria=3)
        return render(request, 'pianos.html', {
            'productos' : productos
        })

class DrumsView(View):
    def get(self, request):
        productos = Instrumento.objects.filter(categoria=4)
        return render(request, 'baterias.html', {
            'productos' : productos
        })
            
class ViolinesView(View):
    def get(self, request):
        productos = Instrumento.objects.filter(categoria=5)
        return render(request, 'violines.html', {
            'productos' : productos
        })

class OrchestraView(View):
    def get(self, request):
        productos = Instrumento.objects.filter(Q(categoria=6) | Q(categoria=3) | Q(categoria=5))
        return render(request, 'orquesta.html', {
            'productos' : productos
        })
 
class ConfirmPurchaseView(LoginRequiredMixin, View):
    login_url = '/iniciar_sesion/'

    def handle_no_permission(self):
        messages.error(self.request, "Debe iniciar sesión para realizar una compra.")
        return redirect(self.login_url)

    def get(self, request):
        return render(request, 'confirmar_compra.html')

    def post(self, request):
        usuario = request.user
        nombre_comprador = request.POST.get('nombre_comprador')
        correo = request.POST.get('correo')
        telefono = request.POST.get('telefono')
        productos = request.POST.get('productos').split(',')
        cantidades = request.POST.get('cantidad_productos').split(',')
        precio_final = request.POST.get('precio_final')

        if len(productos) != len(cantidades):
            error = 'La cantidad de productos seleccionados y la cantidad en stock no coinciden!.'
            return render(request, 'confirmar_compra.html', {

MusicDLC/templates/agregar_categorias.html
{% extends 'layouts/base.html' %}

{% block content %}

    <div class="contenedor__formularios">
        <div>
            <h1>Agregar Categorias</h1>
            <h3 class="mensaje__Success">{{ mensaje }}</h3>
            {% if messages %}
                {% for message in messages %}
                    <h3 class="mensaje__Success">{{ message }}</h3>
                {% endfor %}
            {% endif %}
            <h3 class="mensaje__Error">{{ error }}</h3>
        </div>

        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" name="marca_form">Agregar Categoria</button>
        </form>
    </div>

{% endblock %}

MusicDLC/templates/agregar_marcas.html
{% extends 'layouts/base.html' %}

{% block content %}

    <div class="contenedor__formularios">
        <div>
            <h1>Agregar Marcas</h1>
            <h3 class="mensaje__Success">{{ mensaje }}</h3>
            {% if messages %}
                {% for message in messages %}
                    <h3 class="mensaje__Success">{{ message }}</h3>
                {% endfor %}
            {% endif %}
            <h3 class="mensaje__Error">{{ error }}</h3>
        </div>

        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" name="marca_form">Agregar Marca</button>
        </form>
    </div>

{% endblock %}

MusicDLC/templates/agregar_productos.html
{% extends 'layouts/base.html' %}

{% block content %}

    <div class="contenedor__formularios">
        <div>
            <h1>Agregar Producto Nuevo</h1>
            <h3 class="mensaje__Success">{{ mensaje }}</h3>
            {% if messages %}
                {% for message in messages %}
                    <h3 class="mensaje__Success">{{ message }}</h3>
                {% endfor %}
            {% endif %}
            <h3 class="mensaje__Error">{{ error }}</h3>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-group">
                <label for="nombre">Nombre:</label>
                {{ form.nombre }}
            </div>
            <div class="input-group">
                <label for="descripcion">Descripción:</label>
                {{ form.descripcion }}
            </div>
            <div class="input-group">
                <label for="precio">Precio:</label>
                {{ form.precio }}
            </div>
            <div class="input-group">
                <label for="cantidad">Cantidad:</label>
                {{ form.cantidad }}
            </div>
            <div class="input-group">
                <label for="disponibilidad">Disponibilidad:</label>
                <div class="checkbox-container">
                    {{ form.disponibilidad }}
                </div>
            </div>        
            <div class="input-group">
                <label for="marca">Marca:</label>
                {{ form.marca }}
            </div>
            <div class="input-group">
                <label for="categoria">Categoría:</label>
                {{ form.categoria }}
            </div>
            <div class="input-group">
                <label for="imagen">Imagen:</label>
                {{ form.imagen }}
            </div>
            <button class="btn-guardar">Guardar</button>
        </form>
    </div>

{% endblock %}

MusicDLC/templates/audio.html
{% extends 'layouts/base.html' %}

{% block content %}

    <div class="section__instrumentos">
        <div class="section__instrumentos-container">
            <div class="section__instrumentos-title">
                <h2>Equipos de Audio de gran calidad</h2>
            </div>
            <div class="section__instrumentos-cards">
                {% for producto in productos %}
                    <div class="section__instrumentos-cards-card" data-aos="fade-down" data-aos-duration="1000">
                        <img src="{{ producto.imagen.url }}" alt="Imagen No disponible del Producto" class="productos__img">
                        <p>{{ producto.marca }}</p>
                        <h2 class="productos__titulo">{{ producto.nombre }}</h2>
                        <p>${{ producto.precio|floatformat:2 }}MXN</p>
                        <button class="añadir_al_carrito" data-product-id="{{ producto.id }}" data-product-price="{{ producto.precio }}">Añadir al Carrito</button>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

MusicDLC/templates/bajos.html
{% extends 'layouts/base.html' %}

{% block title %} Bajos {% endblock %}

{% block content %}

    <div class="section__instrumentos">
        <div class="section__instrumentos-container">
            <div class="section__instrumentos-title">
                <h2>Los Bajos de Mayor Calidad solo Aquí</h2>
            </div>
            <div class="section__instrumentos-cards">
                {% for producto in productos %}
                    <div class="section__instrumentos-cards-card" data-aos="fade-down" data-aos-duration="1000">
                        <img src="{{ producto.imagen.url }}" alt="Imagen No disponible del Producto" class="productos__img">
                        <p>{{ producto.marca }}</p>
                        <h2 class="productos__titulo">{{ producto.nombre }}</h2>
                        <p>${{ producto.precio|floatformat:2 }}MXN</p>
                        <button class="añadir_al_carrito" data-product-id="{{ producto.id }}" data-product-price="{{ producto.precio }}">Añadir al Carrito</button>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

MusicDLC/templates/baterias.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %} Baterias {% endblock %}

{% block content %}

    <div class="section__instrumentos">
        <div class="section__instrumentos-container">
            <div class="section__instrumentos-title">
                <h2>Desata tu energía y ritmo con las mejores Baterías</h2>
            </div>
            <div class="section__instrumentos-cards">
                {% for producto in productos %}
                    <div class="section__instrumentos-cards-card" data-aos="fade-down" data-aos-duration="1000">
                        <img src="{{ producto.imagen.url }}" alt="Imagen No disponible del Producto" class="productos__img">
                        <p>{{ producto.marca }}</p>
                        <h2 class="productos__titulo">{{ producto.nombre }}</h2>
                        <p>${{ producto.precio|floatformat:2 }}MXN</p>
                        <button class="añadir_al_carrito" data-product-id="{{ producto.id }}" data-product-price="{{ producto.precio }}">Añadir al Carrito</button>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

MusicDLC/templates/confirmar_compra.html
{% extends 'layouts/base.html' %}

{% block title %} Confirmación de Compra {% endblock %}

{% block content %}

    <div class="contenedor__formularios">
        <div class="contenedor__titulo">
            <h1>Muchas gracias por preferirnos!</h1>
        </div>
        <form id="productos-form" method="POST">
            {% csrf_token %}
            {% if error %}
                <h3 class="mensaje__Error">{{ error }}</h3>
            {% endif %}

            <div class="input-group">
                <label for="id_nombre_comprador">Nombre del comprador:</label><br>
                <input type="text" name="nombre_comprador" maxlength="100" class="form-control" placeholder="Nombre del comprador" required id="id_nombre_comprador">
            </div>
            <div class="input-group">
                <label for="id_correo">Correo electrónico:</label><br>
                <input type="email" name="correo" class="form-control" placeholder="Correo electrónico" required id="id_correo">
            </div>
            <div class="input-group">
                <label for="id_telefono">Número de teléfono:</label><br>
                <input type="text" name="telefono" maxlength="20" class="form-control" placeholder="Número de teléfono" required id="id_telefono">
            </div>
            <div class="input-group">
                <label for="cantidad">Cantidad:</label><br>
                <input type="text" name="cantidad_productos" class="form-control" id="cantidad_productos" readonly>
            </div>
            <div class="input-group">
                <label for="productos">Productos:</label><br>
                <input type="text" name="productos" class="form-control" id="productos" readonly>
            </div>
            <div class="input-group">
                <label for="id_precio_final">Precio final:</label><br>
                <input type="text" id="precio_final" name="precio_final" class="form-control" readonly>
            </div>
            <button type="submit" id="submit-btn">Comprar</button>
        </form>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const urlParams = new URLSearchParams(window.location.search);
            
            const productos = urlParams.get('productos');
            document.getElementById('productos').value = productos;

            const cantidades = urlParams.get('cantidades');
            document.getElementById('cantidad_productos').value = cantidades;
            
            const precioFinal = urlParams.get('precio_final');
            document.getElementById('precio_final').value = precioFinal;
        });
    </script>

{% endblock %}

MusicDLC/templates/email_template.html
Mensaje: {{ message }}

Enviado por: {{ name }} desde la página oficial de MusicDLC, dónde la calidad en el sonido es nuestra prioridad en todos tus instrumentos favoritos

Email del Usuario: {{ email }}

MusicDLC/templates/guitarras.html
{% extends 'layouts/base.html' %}

{% block title %} Guitarras {% endblock %}

{% block content %}

    <div class="section__instrumentos">
        <div class="section__instrumentos-container">
            <div class="section__instrumentos-title">
                <h2>Las Mejores Guitarras Aquí</h2>
            </div>
            <div class="section__instrumentos-cards">
                {% for producto in productos %}
                    <div class="section__instrumentos-cards-card" data-aos="fade-down" data-aos-duration="1000">
                        <img src="{{ producto.imagen.url }}" alt="Imagen No disponible del Producto" class="productos__img">
                        <p>{{ producto.marca }}</p>
                        <h2 class="productos__titulo">{{ producto.nombre }}</h2>
                        <p>${{ producto.precio|floatformat:2 }}MXN</p>
                        <button class="añadir_al_carrito" data-product-id="{{ producto.id }}" data-product-price="{{ producto.precio }}">Añadir al Carrito</button>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

MusicDLC/templates/iniciar_sesion.html
{% extends 'layouts/base.html' %}

{% block content %}

    <main>
        <div class="contenedor__todo">
            <div class="caja__trasera">
                <div class="caja__trasera-login">
                    <h3>¿Ya tienes una cuenta?</h3>
                    <p>Inicia sesión para entrar en la página</p>
                    <button id="btn__iniciar-sesion">Iniciar Sesión</button>
                </div>
                <div class="caja__trasera-register">
                    <h3>¿Aún no tienes una cuenta?</h3>
                    <p>Registrate ahora para poder iniciar sesión</p>
                    <button id="btn__registrarse">Registrarse</button>
                </div>
            </div>
            <div class="contenedor__login-register">
                <form method="POST" class="formulario__login">
                    <h2>Iniciar Sesión</h2>
                    {% csrf_token %}
                    {% if messages %}
                        {% for message in messages %} 
                            <h3 class="mensaje__Error">{{ message }}</h3>
                        {% endfor %}
                    {% endif %}
                    
                    {% if errorLogin %}
                        <h3 class="mensaje__Error">{{ errorLogin }}</h3>
                    {% endif %}
                    <div>
                        <label>Nombre de Usuario</label>
                        {{ formLogin.username }}
                    </div>
                    <div>
                        <label>Contraseña</label>
                        {{ formLogin.password }}
                    </div>
                    <button name="login" type="submit">Entrar</button>
                </form>
                <form method="POST" class="formulario__register">
                    <h2>Registrarse</h2>
                    {% csrf_token %}
                    
                    {% if errorRegister %}
                        <h3 class="mensaje__Error">{{ errorRegister }}</h3>
                        {% for field, errors in registerErrors.items %}
                            <div>
                                <h4>{{ field }}</h4>
                                <ul>
                                    {% for error in errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                    <br>
                                </ul>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <div>
                        <label>Nombre de Usuario</label>
                        {{ formRegister.username }}
                    </div>
                    <div>
                        <label>Contraseña</label>
                        {{ formRegister.password1 }}
                    </div>
                    <div>
                        <label>Confirmar Contraseña</label>
                        {{ formRegister.password2 }}
                    </div>
                    <button name="register" type="submit">Registrarse</button>
                </form>
            </div>            
        </div>
    </main>

{% endblock %}